### ISSUE TITLE
Panic: slice bounds out of range

### ISSUE THREAD

**Issue by dr3amr** [toxuin/alarmserver#26]
Hi,

I get bellow error few times a day and the container crashes:

```
panic: runtime error: slice bounds out of range [-1:]
goroutine 36 [running]:
github.com/toxuin/alarmserver/servers/hisilicon.(*Server).handleTcpConnection(0xc000184180, {0x997eb8?, 0xc00000e030})
	/tmp/app/servers/hisilicon/server.go:61 +0x805
created by github.com/toxuin/alarmserver/servers/hisilicon.(*Server).Start.func2
	/tmp/app/servers/hisilicon/server.go:126 +0x105
```
I have only debug:true, hisilicon and mqtt enabled. What can I do? I see there is a .handleTcpConnection method involved, which connection alarm->mqtt or camera->alarm?

**Comment by toxuin** [comment]
This is a bug, thank you for finding it! It happens when camera sends a string that is not a valid JSON and because there is not sufficient checking for such condition right now - it crashes the app, while it should just be ignored.
What camera is doing that?

**Comment by dr3amr** [comment]
I have 4x Misecu 5mp PoE cameras like bellow. Wifi is unstable but seems also PoE is unstable. This seems like a generic camera as I saw it with different names on Aliexpress.
https://a.aliexpress.com/_EI9XKcr

**Comment by dr3amr** [comment]
@toxuin any ideea if this is hard to implement / fix?

**Comment by dr3amr** [comment]
At the moment I have setup a rule to automatically restart the container on failure thus it is almost always available and listening for "alarms" from the AI cameras. I have an automation to turn on outside lights on human detection thus the alarm server is useful, as at the moment I do not have to use Frigate which melts the CPU as I have no Coral to help.

**Comment by aguscaba** [comment]
> This is a bug, thank you for finding it! It happens when camera sends a string that is not a valid JSON and because there is not sufficient checking for such condition right now - it crashes the app, while it should just be ignored. What camera is doing that?

Hi @toxuin in my case the one who is sending non valid JSON stuff is the load balancer, in order to have my alarm server always up I setup a LB in front of my alarm server and created 2 of them (alarm servers) but instantally they went down :(

**Comment by LucaZiegler** [comment]
I got this with hikvision camera:
```
2025/07/16 15:26:06 hikvisionhaustuer event: videoloss (inactive - 1)
panic: runtime error: slice bounds out of range [-1:]

goroutine 58 [running]:
github.com/toxuin/alarmserver/servers/hisilicon.(*Server).handleTcpConnection(0xc000107410, {0x9a5390?, 0xc00002a358})
        /tmp/app/servers/hisilicon/server.go:61 +0x7d0
created by github.com/toxuin/alarmserver/servers/hisilicon.(*Server).Start.func2 in goroutine 19
        /tmp/app/servers/hisilicon/server.go:126 +0xfc
```
